modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issuetrackerURL="https://github.com/stalexandre//issues"

[[mods]]
modId="mfbt"
displayName="Magical Fantasy Bagel Tweaks"
version="1.20.1-0.0.1"
description='''
Intended to be paired with the datapack, this mod works as a server-side booster for greater flexibility.
'''
#updateJSONURL="https://github.com/stalexandre//"
authors="stalexandre"
displayURL="https://github.com/stalexandre//"
displayTest="IGNORE_SERVER_VERSION"
features={java_version = "17"}
[[dependencies.mfbt]]
modId = "forge"
mandatory = true
versionRange = "[47.1.0,)"
ordering = "NONE"
side = "SERVER"