modLoader="javafml"
loaderVersion="[47.3.1,)"
license="MIT"
issuetrackerURL="https://github.com/stalexandre//issues"

[[mods]]
modId="mfbt"
displayName="Magical Fantasy Bagel Tweaks"
version="1.20.1-0.0.1"
description='''
Intended to be paired with the datapack, this mod works as a Forge port of eclipseisoffline's Modify Player Data mod.
'''
#updateJSONURL="https://github.com/stalexandre//"
authors="stalexandre"
credits="Thanks to eclipseisoffline for the original fabric code that this mod is based off from."
displayURL="https://github.com/stalexandre//"
displayTest="IGNORE_SERVER_VERSION"
features={java_version = "17"}